### ISSUE TITLE
Variable Scope behaviour fails

### ISSUE THREAD

**Issue by lukx** [jeremyworboys/node-kit#9]
According to https://incident57.com/codekit/help.html#kit there is only one contextual scope following from top to bottom, through imports. So if I include _vars.kit from within index.kit, I should have the variables declared in _vars.kit available.

However, due to the cloning of the this._variables object, node-kit opens a new sub-scope to each import. I am testing a solution to this, and will open a PR afterwards.

**Comment by fabiandeneux** [comment]
I can confirm the above referenced issue.

**Comment by fatso83** [comment]
@fdeneux : after reading through this again, and reading that issue in gulp-kit, I am not sure I understand  what you are referring to.

Do you talk about an error in node-kit, because it seems that was resolved last year (ref the closing date). Can you in that case please open a _new_ issue and post a test case (input, expected output, actual output)? This issue has been closed, and until there is some evidence it has problems then it should be regarded it as fixed.

**Comment by fatso83** [comment]
@fdeneux : I have now tested this, and it is working fine. You will need to supply a test case that is reproducible. If you are having problems it is likely you are using an old version of node-kit
